version: "3"

services:
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    platform: linux/arm64/v8
    ports:
      - "3307:3306"
    command:
      - --bind-address=0.0.0.0
      - --default-authentication-plugin=mysql_native_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./plugins/virtual-staging-api:/var/www/html/wp-content/plugins/virtual-staging-api
      - ./plugins/virtual-staging-form-adapter:/var/www/html/wp-content/plugins/virtual-staging-form-adapter
      - ./plugins/api-test-plugin:/var/www/html/wp-content/plugins/api-test-plugin
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    platform: linux/arm64/v8

volumes:
  db_data:
